unstable_features = true
force_multiline_blocks = false
format_macro_bodies = false
fn_single_line = true
max_width = 120
inline_attribute_width = 15
blank_lines_upper_bound = 3
binop_separator = "Back"
reorder_imports = false